# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NativeAppbyXCode' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NativeAppbyXCode
  pod 'lottie-ios'


  target 'NativeAppbyXCodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NativeAppbyXCodeUITests' do
    # Pods for testing
  end


end
